import 'dart:convert';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/services.dart';
import 'package:pactindo_task_ui/model/eula_model.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

const String kNavigationExamplePage = '''
<!DOCTYPE html><html>
<head><title>Navigation Delegate Example</title></head>
<body>
<p><strong>End-User License Agreement ("Agreement")</strong></p>
<p>Our EULA was last updated on 07-01-2022</p>
<p>Please read this End-User License Agreement carefully before clicking the "I Agree" button, downloading or using PACTINDO APP.</p>
<p><strong>Interpretation and Definitions</strong></p>
<p><strong>Interpretation</strong></p>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<p><strong>Definitions</strong></p>
<p>For the purposes of this End-User License Agreement:</p>
<ul>
<li>
<p><strong>"Agreement"</strong> means this End-User License Agreement that forms the entire agreement between You and the Company regarding the use of the Application. This EULA was generated by <a href="https://pactindo.com/home.php">TermsFeed Sarana Pactindo</a>.</p>
</li>
<li>
<p><strong>"Application"</strong> means the software program provided by the Company downloaded by You through an Application Store's account to a Device, named PACTINDO APP</p>
</li>
<li>
<p><strong>"Application Store"</strong> means the digital distribution service operated and developed by Apple Inc. (Apple App Store) or Google Inc. (Google Play Store) by which the Application has been downloaded to your Device.</p>
</li>
<li>
<p><strong>"Company"</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PT Sarana Pactindo</p>
</li>
<li>
<p><strong>"Content"</strong> refers to content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content.</p>
</li>
<li>
<p><strong>"Country"</strong> refers to: Indonesia</p>
</li>
<li>
<p><strong>"Device"</strong> means any device that can access the Application such as a computer, a cellphone or a digital tablet.</p>
</li>
<li>
<p><strong>"Family Sharing / Family Group"</strong> permits You to share applications downloaded through the Application Store with other family members by allowing them to view and download each others' eligible Applications to their associated Devices.</p>
</li>
<li>
<p><strong>"Third-Party Services"</strong> means any services or content (including data, information, applications and other products services) provided by a third-party that may be displayed, included or made available by the Application.</p>
</li>
<li>
<p><strong>"You"</strong> means the individual accessing or using the Application or the company, or other legal entity on behalf of which such individual is accessing or using the Application, as applicable.</p>
</li>
</ul>
<p><strong>Acknowledgment</strong></p>
<p>By clicking the "I Agree" button, downloading or using the Application, You are agreeing to be bound by the terms and conditions of this Agreement. If You do not agree to the terms of this Agreement, do not click on the "I Agree" button, do not download or do not use the Application.</p>
<p>This Agreement is a legal document between You and the Company and it governs your use of the Application made available to You by the Company.</p>
<p>This Agreement is between You and the Company only and not with the Application Store. Therefore, the Company is solely responsible for the Application and its content. Although the Application Store is not a party to this Agreement, it has the right to enforce it against You as a third party beneficiary relating to your use of the Application.</p>
<p>Since the Application can be accessed and used by other users via, for example, Family Sharing / Family Group or volume purchasing, the use of the Application by those users is expressly subject to this Agreement.</p>
<p>The Application is licensed, not sold, to You by the Company for use strictly in accordance with the terms of this Agreement.</p>
<p><strong>License</strong></p>
<p><strong>Scope of License</strong></p>
<p>The Company grants You a revocable, non-exclusive, non-transferable, limited license to download, install and use the Application strictly in accordance with the terms of this Agreement.</p>
<p>You may only use the Application on a Device that You own or control and as permitted by the Application Store's terms and conditions.</p>
<p>The license that is granted to You by the Company is solely for your personal, non-commercial purposes strictly in accordance with the terms of this Agreement.</p>
<p><strong>License Restrictions</strong></p>
<p>You agree not to, and You will not permit others to:</p>
<ul>
<li>
<p>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the Application or make the Application available to any third party.</p>
</li>
<li>
<p>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of the Company or its affiliates, partners, suppliers or the licensors of the Application.</p>
</li>
</ul>
<p><strong>Intellectual Property</strong></p>
<p>The Application, including without limitation all copyrights, patents, trademarks, trade secrets and other intellectual property rights are, and shall remain, the sole and exclusive property of the Company.</p>
<p>The Company shall not be obligated to indemnify or defend You with respect to any third party claim arising out of or relating to the Application. To the extent the Company is required to provide indemnification by applicable law, the Company, not the Application Store, shall be solely responsible for the investigation, defense, settlement and discharge of any claim that the Application or your use of it infringes any third party intellectual property rights.</p>
<p><strong>Modifications to the Application</strong></p>
<p>The Company reserves the right to modify, suspend or discontinue, temporarily or permanently, the Application or any service to which it connects, with or without notice and without liability to You.</p>
<p><strong>Updates to the Application</strong></p>
<p>The Company may from time to time provide enhancements or improvements to the features/functionality of the Application, which may include patches, bug fixes, updates, upgrades and other modifications.</p>
<p>Updates may modify or delete certain features and/or functionalities of the Application. You agree that the Company has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the Application to You.</p>
<p>You further agree that all updates or any other modifications will be (i) deemed to constitute an integral part of the Application, and (ii) subject to the terms and conditions of this Agreement.</p>
<p><strong>Maintenance and Support</strong></p>
<p>The Company does not provide any maintenance or support for the download and use of the Application. To the extent that any maintenance or support is required by applicable law, the Company, not the Application Store, shall be obligated to furnish any such maintenance or support.</p>
<p><strong>Third-Party Services</strong></p>
<p>The Application may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services.</p>
<p>You acknowledge and agree that the Company shall not be responsible for any Third-party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. The Company does not assume and shall not have any liability or responsibility to You or any other person or entity for any Third-party Services.</p>
<p>You must comply with applicable Third parties' Terms of agreement when using the Application. Third-party Services and links thereto are provided solely as a convenience to You and You access and use them entirely at your own risk and subject to such third parties' Terms and conditions.</p>
<p><strong>Term and Termination</strong></p>
<p>This Agreement shall remain in effect until terminated by You or the Company.<br/>
The Company may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</p>
<p>This Agreement will terminate immediately, without prior notice from the Company, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the Application and all copies thereof from your Device or from your computer.</p>
<p>Upon termination of this Agreement, You shall cease all use of the Application and delete all copies of the Application from your Device.</p>
<p>Termination of this Agreement will not limit any of the Company's rights or remedies at law or in equity in case of breach by You (during the term of this Agreement) of any of your obligations under the present Agreement.</p>
<p><strong>Indemnification</strong></p>
<p>You agree to indemnify and hold the Company and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the Application; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>
<p><strong>No Warranties</strong></p>
<p>The Application is provided to You "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Application, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Application will meet your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
<p>Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Application, or the information, content, and materials or products included thereon; (ii) that the Application will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Application; or (iv) that the Application, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
<p>Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law. To the extent any warranty exists under law that cannot be disclaimed, the Company, not the Application Store, shall be solely responsible for such warranty.</p>
<p><strong>Limitation of Liability</strong></p>
<p>Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You for the Application or through the Application or 100 USD if You haven't purchased anything through the Application.</p>
<p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Application, third-party software and/or third-party hardware used with the Application, or otherwise in connection with any provision of this Agreement), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
<p>Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to You.</p>
<p>You expressly understand and agree that the Application Store, its subsidiaries and affiliates, and its licensors shall not be liable to You under any theory of liability for any direct, indirect, incidental, special consequential or exemplary damages that may be incurred by You, including any loss of data, whether or not the Application Store or its representatives have been advised of or should have been aware of the possibility of any such losses arising.</p>
<p><strong>Severability and Waiver</strong></p>
<p><strong>Severability</strong></p>
<p>If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
<p><strong>Waiver</strong></p>
<p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach.</p>
<p><strong>Product Claims</strong></p>
<p>The Company does not make any warranties concerning the Application. To the extent You have any claim arising from or relating to your use of the Application, the Company, not the Application Store, is responsible for addressing any such claims, which may include, but not limited to: (i) any product liability claims; (ii) any claim that the Application fails to conform to any applicable legal or regulatory requirement; and (iii) any claim arising under consumer protection, or similar legislation.</p>
<p><strong>United States Legal Compliance</strong></p>
<p>You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a "terrorist supporting" country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
<p><strong>Changes to this Agreement</strong></p>
<p>The Company reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at the sole discretion of the Company.</p>
<p>By continuing to access or use the Application after any revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, You are no longer authorized to use the Application.</p>
<p><strong>Governing Law</strong></p>
<p>The laws of the Country, excluding its conflicts of law rules, shall govern this Agreement and your use of the Application. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
<p><strong>Entire Agreement</strong></p>
<p>The Agreement constitutes the entire agreement between You and the Company regarding your use of the Application and supersedes all prior and contemporaneous written or oral agreements between You and the Company.</p>
<p>You may be subject to additional terms and conditions that apply when You use or purchase other Company's services, which the Company will provide to You at the time of such use or purchase.</p>
<p><strong>Contact Us</strong></p>
<p>If you have any questions about this Agreement, You can contact Us:</p>
<ul>
<li>By visiting this page on our website: https://pactindo.com/home.php</li>
<li>By sending us an email: saranapactindo@pactinco.com</li>
</ul>
<p></p>
</body>
</html>
''';

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.

        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      builder: (context, value, g) {
        return MaterialApp(
          initialRoute: '/eula',
          debugShowCheckedModeBanner: false,
          routes: {
            '/main': (ctx) => HomePage(),
            '/eula': (ctx) => EulaPage(),
            '/ktp': (ctx) => KtpPage(),
            '/email': (ctx) => EmailPage(),
            '/otp': (ctx) => OtpPage(),
            '/username': (ctx) => UsernamePage(),
            '/password': (ctx) => PasswordPage(),
            '/mpin': (ctx) => MpinPage(),
            '/resi': (ctx) => ResiPage(),
          },
        );
      },
      valueListenable: ValueNotifier(1),
    );
  }
}

class ButtonItem extends StatelessWidget {
  late final String route;

  ButtonItem(this.route);

  @override
  Widget build(BuildContext context) {
    return ListTile(
      onTap: () {
        Navigator.pushNamed(context, route);
      },
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  PageController tabController = PageController();
  int _selectedTab = 0;

  void onTappedTab(int index) {
    setState(() {
      _selectedTab = index;
    });
    tabController.jumpToPage(index);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Color(0xfff58220),
        leading: Builder(
          builder: (BuildContext context) {
            return IconButton(
              icon: const Icon(Icons.menu),
              onPressed: () {
                Scaffold.of(context).openDrawer();
              },
              tooltip: MaterialLocalizations.of(context).openAppDrawerTooltip,
            );
          },
        ),
        title: Text("Tepat"),
        centerTitle: true,
        actions: [
          IconButton(
            icon: const Icon(Icons.notifications),
            onPressed: () {
              Scaffold.of(context).openDrawer();
            },
            tooltip: MaterialLocalizations.of(context).openAppDrawerTooltip,
          ),
        ],
      ),
      body: PageView(
        controller: tabController,
        children: [
          Beranda(),
          Info(),
          Histori(),
          Akun(),
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Beranda'),
          BottomNavigationBarItem(icon: Icon(Icons.info), label: 'Info'),
          BottomNavigationBarItem(icon: Icon(Icons.history), label: 'Histori'),
          BottomNavigationBarItem(icon: Icon(Icons.person), label: 'Akun'),
        ],
        currentIndex: _selectedTab,
        selectedItemColor: Colors.orange,
        unselectedItemColor: Colors.grey,
        onTap: onTappedTab,
      ),
    );
  }
}

class EulaPage extends StatefulWidget {
  // final AssetBundle rootBundle = _initRootBundle();
  @override
  _EulaPageState createState() => _EulaPageState();
}

class _EulaPageState extends State<EulaPage> {
  bool isChecked = false;

  String contentBase64 = "";

  initState() {
    super.initState();
  }

  Future<EulaModel> loadJsonData() async { /* Jadikan return data dengan model data eula */
    var jsonText = await rootBundle.loadString('assets/data/dummy_html.json');
    String eulaData = jsonText;
    EulaModel eula = EulaModel.fromJson(jsonDecode(eulaData));
    return eula;
  }

  Widget build(BuildContext context) {
    // loadJsonData();
    print('AKKKKKMMMMMMMMMMM');
    print(loadJsonData());
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Color(0xfff58220),
        title: Text("EULA"),
        centerTitle: true,
      ),
      body: FutureBuilder( /* Pakai future builder buat get data asynchronous */
        future: loadJsonData(),
        builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
          if (snapshot.hasData) { /* Cek apakah datanya ada atau tidak, kalau ada tampilkan widget webview, kalau tidak tampilkan loading */
            return Container(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Container(
                    height: MediaQuery.of(context).size.height * 0.8,
                    child: WebView(
                      initialUrl: 'data:text/html;base64,${base64Encode(const Utf8Encoder().convert(snapshot.data.eulaHtml))}',
                    ),
                  ),
                  Container(
                    padding: EdgeInsets.all(8.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Checkbox(
                            value: isChecked,
                            onChanged: (bool? value) { /* Set state ketika checkbox ditap/dikasih action */
                              setState(() {
                                isChecked = value!;
                              });
                            }),
                        Container(
                          width: MediaQuery.of(context).size.width * 0.8,
                          child: TextButton(
                            style: TextButton.styleFrom(
                              backgroundColor: Colors.orange,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(20),
                              ),
                            ),
                            onPressed: () {
                              if (isChecked) { /* Kasih validasi kalau checkbox belum diceklis, button gaboleh ada aksi */
                                Navigator.pushNamed(context, '/main');
                                setState(() {
                                  isChecked = false;
                                });
                                print('I Agree Clicked');
                              }
                            },
                            child: Text(
                              "I Agree",
                              style: TextStyle(
                                fontSize: 17,
                                color: Color(0xffffffff),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            );
          }
          return Center(child: CircularProgressIndicator());
        },
      ),
    );
  }
}

class KtpPage extends StatelessWidget {
  const KtpPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class EmailPage extends StatelessWidget {
  const EmailPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class OtpPage extends StatelessWidget {
  const OtpPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class UsernamePage extends StatelessWidget {
  const UsernamePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class PasswordPage extends StatelessWidget {
  const PasswordPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class MpinPage extends StatelessWidget {
  const MpinPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class ResiPage extends StatelessWidget {
  const ResiPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Beranda extends StatelessWidget {
  Beranda({Key? key}) : super(key: key);

  final List<Container> myGrid = List.generate(8, (index) {
    final List<String> gridText = [
      'Rekening Saya',
      'Transfer',
      'Pembelian',
      'Pembayaran',
      'Favorit',
      'Transaksi Terjadwal',
      'Layanan Islami',
      'Semua Menu'
    ];
    return Container(
      child: Center(child: Text(gridText[index])),
      decoration: BoxDecoration(
        color: Color.fromARGB(255, Random().nextInt(255), Random().nextInt(255),
            Random().nextInt(255)),
        borderRadius: BorderRadius.circular(5),
      ),
    );
  });
  final List<Color> myColor = [
    Colors.orange,
    Colors.blue,
    Colors.green,
    Colors.amber,
    Colors.red
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
            padding: EdgeInsets.all(10),
            color: Colors.lightBlue[100],
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Bandung Wetan, Dzuhur 12:08',
                ),
                Text(
                  "11 Sya'ban 1442 H",
                ),
              ],
            )),
        Expanded(
          child: ListView(
            // padding: EdgeInsets.only(bottom: 32),
            children: [
              Container(
                margin: EdgeInsets.only(left: 20, top: 10),
                child: Text(
                  "Assalamu'alaikum, Muhammad Imam",
                ),
              ),
              Container(
                child: CarouselSlider(
                  options: CarouselOptions(
                    height: 180,
                    enableInfiniteScroll: false,
                    viewportFraction: 0.92,
                    autoPlay: true,
                  ),
                  items: [1, 2, 3, 4, 5]
                      .map((item) => Container(
                            margin: EdgeInsets.symmetric(
                                horizontal: 6, vertical: 15),
                            child: Center(child: Text(item.toString())),
                            decoration: BoxDecoration(
                              color: myColor[item - 1],
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ))
                      .toList(),
                ),
              ),
              Container(
                height: 190,
                // color: Colors.lightBlue,
                child: GridView.count(
                  physics: NeverScrollableScrollPhysics(),
                  // primary: false,
                  padding: const EdgeInsets.all(20),
                  crossAxisSpacing: 20,
                  mainAxisSpacing: 20,
                  crossAxisCount: 4,
                  children: myGrid,
                ),
              ),
              Container(
                child: CarouselSlider(
                  options: CarouselOptions(
                    height: 180,
                    enableInfiniteScroll: false,
                    viewportFraction: 0.92,
                    autoPlay: true,
                  ),
                  items: [1, 2, 3, 4, 5]
                      .map((item) => Container(
                            margin: EdgeInsets.symmetric(
                                horizontal: 6, vertical: 15),
                            child: Center(child: Text(item.toString())),
                            decoration: BoxDecoration(
                              color: myColor[item - 1],
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ))
                      .toList(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class Info extends StatelessWidget {
  Info({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
          child: Text(
        'Tab Info',
        style: new TextStyle(fontSize: 40),
      )),
    );
  }
}

class Histori extends StatelessWidget {
  Histori({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
          child: Text(
        'Tab History',
        style: new TextStyle(fontSize: 40),
      )),
    );
  }
}

class Akun extends StatelessWidget {
  Akun({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
          child: Text(
        'Tab Akun',
        style: new TextStyle(fontSize: 40),
      )),
    );
  }
}
